spring:
  application:
    name: user-system

server:
  port: 9000                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: user-system         # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
